version: "3.8"
services:
    # BDD
    db:
        image: mysql
        container_name: db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - gedm1

    # phpmyadmin 
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 3306:80
        environment:
            PMA_HOST: db
        networks:
            - gedm1

    # Symfony apache project
    www:
        build: docker/php
        container_name: symfony
        ports:
          - "80:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./project:/var/www/project
        restart: always
        networks:
            - gedm1

networks:
    gedm1:

volumes:
    db-data: